project:
  type: default

format:
  revealjs:
    embed-resources: true
    theme: serif
    slide-number: true
    code-line-numbers: true
    highlight-style: github
    width: 1920
    height: 1080
    margin: 0.02
    css: custom.css
    footer: " "
